let suggestions = [
  "apple",
  "Channel",
  "Subhadip Chatterjee Vlogs",
  "Subhadip Chatterjee",
  "iNeuron.ai",
  "learncodeonline",
  "lco",
  "YouTube",
  "YouTuber",
  "YouTube Channel",
  "Blogger",
  "Bollywood",
  "Vlogger",
  "instagram",
  "Facebook",
  "Freelancer",
  "linkedin",
  "Designer",
  "Developer",
  "Web Designer",
  "Web Developer",
  "Login Form in HTML & CSS",
  "How to learn HTML",
  "How to learn CSS",
  "How to learn Tailwind CSS",
  "How to learn Bootstrap",
  "How to learn JavaScript",
  "How to became Freelancer",
  "How to became Web Designer",
  "How to start Gaming Channel",
  "How to start YouTube Channel",
  "What does HTML stands for?",
  "What does CSS stands for?",
  "what is Tailwind CSS?",
  "What is Bootstrap",
  "How to learn React JS"
];